# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [30]:
# your code here

import numpy as np

#### 2. Print your NumPy version.

In [31]:
# your code here

np.__version__

'1.18.1'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [32]:
# Method 1

a = np.random.random(size=(2,3,5))
a

array([[[0.57602055, 0.84393233, 0.25696653, 0.71244133, 0.74727579],
        [0.74831449, 0.66928486, 0.6512054 , 0.93586804, 0.66729981],
        [0.03733562, 0.82027444, 0.26341584, 0.68382734, 0.22448658]],

       [[0.37133543, 0.36042805, 0.58137449, 0.83027349, 0.20150426],
        [0.57289092, 0.80028221, 0.76941131, 0.21039955, 0.30952289],
        [0.71946101, 0.10541037, 0.62444615, 0.2524541 , 0.84429406]]])

In [33]:
# Method 2

np.array(np.random.random(size=(2,3,5)))

array([[[0.34295926, 0.57028555, 0.56915601, 0.01100443, 0.59521286],
        [0.68074886, 0.86831664, 0.91822875, 0.43050629, 0.02828349],
        [0.32970262, 0.46604596, 0.89114711, 0.70994633, 0.54544709]],

       [[0.93885643, 0.65101324, 0.39363976, 0.29590134, 0.77542642],
        [0.35209785, 0.29886305, 0.81543919, 0.38485274, 0.95738214],
        [0.95781636, 0.10844123, 0.08981575, 0.07355936, 0.48087691]]])

In [34]:
# Method 3

#### 4. Print *a*.


In [35]:
# your code here

a

array([[[0.57602055, 0.84393233, 0.25696653, 0.71244133, 0.74727579],
        [0.74831449, 0.66928486, 0.6512054 , 0.93586804, 0.66729981],
        [0.03733562, 0.82027444, 0.26341584, 0.68382734, 0.22448658]],

       [[0.37133543, 0.36042805, 0.58137449, 0.83027349, 0.20150426],
        [0.57289092, 0.80028221, 0.76941131, 0.21039955, 0.30952289],
        [0.71946101, 0.10541037, 0.62444615, 0.2524541 , 0.84429406]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [36]:
# your code here

b = np.ones((5,2,3))

#### 6. Print *b*.


In [37]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [38]:
# your code here

if np.size(a) == np.size(b):
    print('a and b have the same size')
else:
    print("a and b don't have the same size")

a and b have the same size


#### 8. Are you able to add *a* and *b*? Why or why not?


In [39]:
# your answer here

try:
    a + b
except:
    print('The shape of the arrays are different.')

The shape of the arrays are different.


#### 9. Reshape *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the reshaped array to variable *c*.

In [40]:
# your code here

c = b.reshape(2,3,5)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [41]:
# your code/answer here

d = a + c
d

print(d)
print('\n')
print('The arrays have the same shape')

[[[1.57602055 1.84393233 1.25696653 1.71244133 1.74727579]
  [1.74831449 1.66928486 1.6512054  1.93586804 1.66729981]
  [1.03733562 1.82027444 1.26341584 1.68382734 1.22448658]]

 [[1.37133543 1.36042805 1.58137449 1.83027349 1.20150426]
  [1.57289092 1.80028221 1.76941131 1.21039955 1.30952289]
  [1.71946101 1.10541037 1.62444615 1.2524541  1.84429406]]]


The arrays have the same shape


#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [42]:
# your code/answer here

print('a: ', a)
print('\n' * 3)
print('d: ', d)
print('\n' * 3)
print('d = a + 1')

a:  [[[0.57602055 0.84393233 0.25696653 0.71244133 0.74727579]
  [0.74831449 0.66928486 0.6512054  0.93586804 0.66729981]
  [0.03733562 0.82027444 0.26341584 0.68382734 0.22448658]]

 [[0.37133543 0.36042805 0.58137449 0.83027349 0.20150426]
  [0.57289092 0.80028221 0.76941131 0.21039955 0.30952289]
  [0.71946101 0.10541037 0.62444615 0.2524541  0.84429406]]]




d:  [[[1.57602055 1.84393233 1.25696653 1.71244133 1.74727579]
  [1.74831449 1.66928486 1.6512054  1.93586804 1.66729981]
  [1.03733562 1.82027444 1.26341584 1.68382734 1.22448658]]

 [[1.37133543 1.36042805 1.58137449 1.83027349 1.20150426]
  [1.57289092 1.80028221 1.76941131 1.21039955 1.30952289]
  [1.71946101 1.10541037 1.62444615 1.2524541  1.84429406]]]




d = a + 1


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [43]:
# your code here

e = a * c
e

array([[[0.57602055, 0.84393233, 0.25696653, 0.71244133, 0.74727579],
        [0.74831449, 0.66928486, 0.6512054 , 0.93586804, 0.66729981],
        [0.03733562, 0.82027444, 0.26341584, 0.68382734, 0.22448658]],

       [[0.37133543, 0.36042805, 0.58137449, 0.83027349, 0.20150426],
        [0.57289092, 0.80028221, 0.76941131, 0.21039955, 0.30952289],
        [0.71946101, 0.10541037, 0.62444615, 0.2524541 , 0.84429406]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [44]:
# your code/answer here

if e.all() == a.all():
    print('e is equal to a')
    print('\nAll values in "a" were multiplied by 1')

e is equal to a

All values in "a" were multiplied by 1


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [45]:
# your code here

d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)

print(f'max = {d_max}, min = {d_min}, mean = {d_mean}')

max = 1.9358680411589195, min = 1.03733562332595, mean = 1.546381241383517


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [265]:
# your code here

f = np.empty((2,3,5))
f

array([[[1.57602055, 1.84393233, 1.25696653, 1.71244133, 1.74727579],
        [1.74831449, 1.66928486, 1.6512054 , 1.93586804, 1.66729981],
        [1.03733562, 1.82027444, 1.26341584, 1.68382734, 1.22448658]],

       [[1.37133543, 1.36042805, 1.58137449, 1.83027349, 1.20150426],
        [1.57289092, 1.80028221, 1.76941131, 1.21039955, 1.30952289],
        [1.71946101, 1.10541037, 1.62444615, 1.2524541 , 1.84429406]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [274]:
lst = []

for lst1 in d:
    for lst2 in lst1:
        for n in lst2:
            if n > d_min and n < d_mean:
                n = 25
            elif n > d_mean and n < d_max:
                n = 75
            elif n == d_mean:
                n = 50
            elif n == d_min:
                n = 0
            elif n == d_max:
                n = 100
            lst.append(n)

f = np.reshape(lst, (2,3,5))


# 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [275]:
# your code here

print(d)
print('\n' * 3)
print(f)

[[[1.57602055 1.84393233 1.25696653 1.71244133 1.74727579]
  [1.74831449 1.66928486 1.6512054  1.93586804 1.66729981]
  [1.03733562 1.82027444 1.26341584 1.68382734 1.22448658]]

 [[1.37133543 1.36042805 1.58137449 1.83027349 1.20150426]
  [1.57289092 1.80028221 1.76941131 1.21039955 1.30952289]
  [1.71946101 1.10541037 1.62444615 1.2524541  1.84429406]]]




[[[ 75  75  25  75  75]
  [ 75  75  75 100  75]
  [  0  75  25  75  25]]

 [[ 25  25  75  75  25]
  [ 75  75  75  25  25]
  [ 75  25  75  25  75]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [276]:
# your code here

lst = []

for lst1 in d:
    for lst2 in lst1:
        for n in lst2:
            if n > d_min and n < d_mean:
                n = 'A'
            elif n > d_mean and n < d_max:
                n = 'B'
            elif n == d_mean:
                n = 'C'
            elif n == d_min:
                n = 'D'
            elif n == d_max:
                n = 'E'
            lst.append(n)

f = np.reshape(lst, (2,3,5))

In [279]:
print(f)

[[['B' 'B' 'A' 'B' 'B']
  ['B' 'B' 'B' 'E' 'B']
  ['D' 'B' 'A' 'B' 'A']]

 [['A' 'A' 'B' 'B' 'A']
  ['B' 'B' 'B' 'A' 'A']
  ['B' 'A' 'B' 'A' 'B']]]
